# Лабораторная работа: HR-датасет сотрудников — подготовка данных к анализу

**Курс:** Data Science & Analytics — Неделя 4: Подготовка данных к анализу

**Ситуация.** Я аналитик данных и работаю с HR-отделом. HR-менеджер попросил подготовить датасет сотрудников
к анализу. В исходных данных есть пропуски, дубликаты, несогласованные записи, неверные типы данных
и даты, сохранённые как текст.

**Цель.** Очистить и подготовить HR-датасет с помощью Pandas: найти проблемы качества данных и решить их
подходящими методами и параметрами.

**Правило.** Исходные датасеты (`employees`, `departments`) не изменяются — вся работа ведётся с копией (`df`).

## Подготовка — исходные датасеты (даны в задании, не изменяются)

In [1]:
import pandas as pd
import numpy as np

# Do not modify this cell.
# Raw HR employee dataset created for data cleaning practice.
employees = pd.DataFrame({
    "EmployeeID": [
        101, 102, 103, 103, 105, 106, 107, 108,
        109, 110, 111, 112, 113, 114, 115
    ],
    "FirstName": [
        "Ainura", "Bakyt", "Gulnara", "Gulnara", "Nurlan",
        "Aigul", "Beksultan", "Aisuluu", "Ermek", "Nurgul",
        "Daniyar", "Aizhan", "Kubat", "Perizat", "Adilet"
    ],
    "LastName": [
        "Asanova", "Kyzylov", "Mamatova", "Mamatova", "Abdyldaev",
        "Sultanova", "Toktogulov", "baisalova", "Kadyrov",
        "Jumabaeva ", "Turgunov", "Ryskulova", "Kadyraliev",
        "BAktybekova", "MOLDOKULOV"
    ],
    "Department": [
        "IT", "HR", "it", "IT", "Finance", "HR",
        " IT ", "Finance", "IT", "HR", "it",
        "Financing", "Information Tecnology", "HR", "finance"
    ],
    "Gender": [
        "F", "m", "F", "f", "M", "F", "M", "F",
        "M", "F", "M", "F", "M", "F", "m"
    ],
    "Age": [
        "28", "35", "29", "29", "150", "31", "33",
        "27", "30", "38", "26", "34", "29", "32", "31"
    ],
    "Salary": [
        "80000", "65000", np.nan, np.nan, "90000", "70000",
        "unknown", "62000", "85000", "58000", "72000",
        "66000", "78000", "88000", "61000"
    ],
    "HireDate": [
        "2023-01-15", "2022-06-10", "2024-03-01", "2024-03-01",
        "2021-11-20", "2023-08-05", "2020-05-12", "2022-09-18",
        "2021-03-25", "2019-07-14", "2023-04-18", "2020-10-02",
        "2022-12-11", "2021-08-30", "2023-06-22"
    ],
    "PerformanceScore": [
        4.2, 3.8, 4.5, 4.5, 4.0, 3.9, 4.1,
        3.7, 4.3, 3.6, 4.4, 3.8, 4.2, "4.0", 3.9
    ]
})

departments = pd.DataFrame({
    "DepartmentID": [1, 2, 3],
    "DepartmentName": ["IT", "HR", "Finance"],
    "Location": ["Bishkek", "Osh", "Bishkek"]
})

In [2]:
# Работаем с копией, чтобы исходный датасет остался без изменений
df = employees.copy()
df

,EmployeeID,FirstName,LastName,Department,Gender,Age,Salary,HireDate,PerformanceScore
0,101,Ainura,Asanova,IT,F,28,80000,2023-01-15,4.2
1,102,Bakyt,Kyzylov,HR,m,35,65000,2022-06-10,3.8
2,103,Gulnara,Mamatova,it,F,29,NaN,2024-03-01,4.5
3,103,Gulnara,Mamatova,IT,f,29,NaN,2024-03-01,4.5
4,105,Nurlan,Abdyldaev,Finance,M,150,90000,2021-11-20,4.0
5,106,Aigul,Sultanova,HR,F,31,70000,2023-08-05,3.9
6,107,Beksultan,Toktogulov,IT,M,33,unknown,2020-05-12,4.1
7,108,Aisuluu,baisalova,Finance,F,27,62000,2022-09-18,3.7
8,109,Ermek,Kadyrov,IT,M,30,85000,2021-03-25,4.3
9,110,Nurgul,Jumabaeva,HR,F,38,58000,2019-07-14,3.6
10,111,Daniyar,Turgunov,it,M,26,72000,2023-04-18,4.4
11,112,Aizhan,Ryskulova,Financing,F,34,66000,2020-10-02,3.8
12,113,Kubat,Kadyraliev,Information Tecnology,M,29,78000,2022-12-11,4.2
13,114,Perizat,BAktybekova,HR,F,32,88000,2021-08-30,4.0
14,115,Adilet,MOLDOKULOV,finance,m,31,61000,2023-06-22,3.9

## Задание 1 — Осмотр датасета

In [3]:
# Количество строк и столбцов
print("Размер (строки, столбцы):", df.shape)
print("Строк:", df.shape[0], "| Столбцов:", df.shape[1])

Размер (строки, столбцы): (15, 9)
Строк: 15 | Столбцов: 9

In [4]:
# Типы данных всех столбцов
df.dtypes

EmployeeID           int64
FirstName              str
LastName               str
Department             str
Gender                 str
Age                    str
Salary                 str
HireDate               str
PerformanceScore    object
dtype: object

In [5]:
# Типы данных выбранных столбцов
df[["Salary", "Age", "HireDate"]].dtypes

Salary      str
Age         str
HireDate    str
dtype: object

In [6]:
# notna() -> True там, где зарплата указана
print(df["Salary"].notna())
print("\nСтрок с указанной зарплатой:", df["Salary"].notna().sum())
df[df["Salary"].notna()]

0      True
1      True
2     False
3     False
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
Name: Salary, dtype: bool

Строк с указанной зарплатой: 13

,EmployeeID,FirstName,LastName,Department,Gender,Age,Salary,HireDate,PerformanceScore
0,101,Ainura,Asanova,IT,F,28,80000,2023-01-15,4.2
1,102,Bakyt,Kyzylov,HR,m,35,65000,2022-06-10,3.8
4,105,Nurlan,Abdyldaev,Finance,M,150,90000,2021-11-20,4.0
5,106,Aigul,Sultanova,HR,F,31,70000,2023-08-05,3.9
6,107,Beksultan,Toktogulov,IT,M,33,unknown,2020-05-12,4.1
7,108,Aisuluu,baisalova,Finance,F,27,62000,2022-09-18,3.7
8,109,Ermek,Kadyrov,IT,M,30,85000,2021-03-25,4.3
9,110,Nurgul,Jumabaeva,HR,F,38,58000,2019-07-14,3.6
10,111,Daniyar,Turgunov,it,M,26,72000,2023-04-18,4.4
11,112,Aizhan,Ryskulova,Financing,F,34,66000,2020-10-02,3.8
12,113,Kubat,Kadyraliev,Information Tecnology,M,29,78000,2022-12-11,4.2
13,114,Perizat,BAktybekova,HR,F,32,88000,2021-08-30,4.0
14,115,Adilet,MOLDOKULOV,finance,m,31,61000,2023-06-22,3.9

In [7]:
# --- Поиск проблем качества данных ---

# 1) Пропуски (считаются только настоящие NaN; текст "unknown" — скрытый пропуск)
print("Пропуски по столбцам:\n", df.isna().sum(), sep="")
print("\nСкрытые пропуски ('unknown' в Salary):", (df["Salary"] == "unknown").sum())

# 2) Дубликаты
print("\nПолных дубликатов строк:", df.duplicated().sum())
print("Повторяющихся EmployeeID:", df.duplicated(subset="EmployeeID").sum())

Пропуски по столбцам:
EmployeeID          0
FirstName           0
LastName            0
Department          0
Gender              0
Age                 0
Salary              2
HireDate            0
PerformanceScore    0
dtype: int64

Скрытые пропуски ('unknown' в Salary): 1

Полных дубликатов строк: 0
Повторяющихся EmployeeID: 1

In [8]:
# Строки с одинаковым EmployeeID
df[df.duplicated(subset="EmployeeID", keep=False)]

,EmployeeID,FirstName,LastName,Department,Gender,Age,Salary,HireDate,PerformanceScore
2,103,Gulnara,Mamatova,it,F,29,NaN,2024-03-01,4.5
3,103,Gulnara,Mamatova,IT,f,29,NaN,2024-03-01,4.5

In [9]:
# 3) Несогласованные названия отделов (регистр, пробелы, опечатки, синонимы)
print("Department:", df["Department"].unique())

# Несогласованные коды пола и регистр фамилий
print("Gender:    ", df["Gender"].unique())
print("LastName:  ", df["LastName"].unique())

Department: <StringArray>
[                   'IT',                    'HR',                    'it',
               'Finance',                  ' IT ',             'Financing',
 'Information Tecnology',               'finance']
Length: 8, dtype: str
Gender:     <StringArray>
['F', 'm', 'f', 'M']
Length: 4, dtype: str
LastName:   <StringArray>
[    'Asanova',     'Kyzylov',    'Mamatova',   'Abdyldaev',   'Sultanova',
  'Toktogulov',   'baisalova',     'Kadyrov',  'Jumabaeva ',    'Turgunov',
   'Ryskulova',  'Kadyraliev', 'BAktybekova',  'MOLDOKULOV']
Length: 14, dtype: str

In [10]:
# 4) Неверный возраст: Age хранится как текст, временно переводим в число для проверки диапазона
age_check = pd.to_numeric(df["Age"], errors="coerce")
print(age_check.describe())
df[~age_check.between(18, 70)]

count     15.000000
mean      38.800000
std       30.926641
min       26.000000
25%       29.000000
50%       31.000000
75%       33.500000
max      150.000000
Name: Age, dtype: float64

,EmployeeID,FirstName,LastName,Department,Gender,Age,Salary,HireDate,PerformanceScore
4,105,Nurlan,Abdyldaev,Finance,M,150,90000,2021-11-20,4.0

In [11]:
# 5) Даты, сохранённые как текст
print("Тип HireDate:", df["HireDate"].dtype)
print("Python-тип первого значения:", type(df.loc[0, "HireDate"]))

Тип HireDate: str
Python-тип первого значения: <class 'str'>

In [12]:
# Лишние пробелы: ищем текстовые значения с пробелами в начале или в конце
for col in df.columns:
    has_spaces = df[col].map(lambda v: isinstance(v, str) and v != v.strip())
    if has_spaces.any():
        print(f"{col}: {df.loc[has_spaces, col].tolist()}")

LastName: ['Jumabaeva ']
Department: [' IT ']

In [13]:
# Удаляем лишние пробелы во всех текстовых значениях (числа не трогаем)
df = df.apply(lambda col: col.map(lambda v: v.strip() if isinstance(v, str) else v))

# Приводим остальные текстовые записи к единому виду: фамилии с заглавной буквы, пол — заглавными
df["LastName"] = df["LastName"].str.title()
df["Gender"] = df["Gender"].str.upper()

print("Department:", df["Department"].unique())
print("Gender:    ", df["Gender"].unique())
print("LastName:  ", df["LastName"].unique())

Department: <StringArray>
['IT', 'HR', 'it', 'Finance', 'Financing', 'Information Tecnology', 'finance']
Length: 7, dtype: str
Gender:     <StringArray>
['F', 'M']
Length: 2, dtype: str
LastName:   <StringArray>
[    'Asanova',     'Kyzylov',    'Mamatova',   'Abdyldaev',   'Sultanova',
  'Toktogulov',   'Baisalova',     'Kadyrov',   'Jumabaeva',    'Turgunov',
   'Ryskulova',  'Kadyraliev', 'Baktybekova',  'Moldokulov']
Length: 14, dtype: str

In [14]:
# Все ли значения PerformanceScore числовые?
print("Тип:", df["PerformanceScore"].dtype)
print(df["PerformanceScore"].map(type).value_counts())
print("\nНечисловые значения (сохранены как текст):")
df.loc[df["PerformanceScore"].map(lambda v: isinstance(v, str)), ["EmployeeID", "PerformanceScore"]]

Тип: object
PerformanceScore
<class 'float'>    14
<class 'str'>       1
Name: count, dtype: int64

Нечисловые значения (сохранены как текст):

    EmployeeID PerformanceScore
13         114              4.0

### Задание 1 — Пояснение

- **Размер:** в исходном датасете **15 строк и 9 столбцов**.
- **Типы данных:** `Age`, `Salary` и `HireDate` хранятся как **текст** (`object`/`str`), а не как числа или даты,
  поэтому по ним нельзя посчитать среднее или работать со временем. `PerformanceScore` имеет тип `object`, потому что
  в нём вместе с числами есть строка `"4.0"`.
- **`notna()`** возвращает `True`, где значение есть: зарплата указана у 13 из 15 строк, но одно из этих значений —
  слово `"unknown"`, то есть *скрытый* пропуск, который `isna()` не видит.

**Найденные проблемы качества данных:**

| Проблема | Где |
|---|---|
| Пропуски | `Salary`: 2 × `NaN` + 1 × `"unknown"` |
| Дубликаты | `EmployeeID` 103 (Gulnara Mamatova) встречается дважды |
| Несогласованные названия отделов | `"it"`, `" IT "`, `"Information Tecnology"`, `"Financing"`, `"finance"` |
| Неверный возраст | у Nurlan Abdyldaev (ID 105) `Age = 150` |
| Даты в виде текста | `HireDate` — строковый столбец |
| Лишние пробелы | `" IT "` в Department, `"Jumabaeva "` в LastName |
| Другие несогласованности | коды пола `m`/`f`, фамилии `baisalova`, `BAktybekova`, `MOLDOKULOV` |
| Нечисловая оценка | `PerformanceScore = "4.0"` (текст) у ID 114 |

Две строки с ID 103 пока **не являются** полными дубликатами — они отличаются только `"it"`/`"IT"` и `"F"`/`"f"`.
Поэтому текст нужно очистить *до* удаления дубликатов.

**Очистка в этом задании:** лишние пробелы удалены из всех текстовых значений с помощью `str.strip()`,
фамилии приведены к виду «с заглавной буквы», коды пола — к заглавным буквам.

## Задание 2 — Обработка пропущенных зарплат

In [15]:
# Пропуски: количество по столбцам и процент
missing = pd.DataFrame({
    "пропусков": df.isna().sum(),
    "процент": (df.isna().mean() * 100).round(2),
})
missing

                  пропусков  процент
EmployeeID                0     0.00
FirstName                 0     0.00
LastName                  0     0.00
Department                0     0.00
Gender                    0     0.00
Age                       0     0.00
Salary                    2    13.33
HireDate                  0     0.00
PerformanceScore          0     0.00

In [16]:
# Заменяем текст "unknown" на настоящий пропуск и переводим Salary в число.
# errors="coerce" превращает всё, что нельзя распознать, в NaN вместо ошибки.
df["Salary"] = df["Salary"].replace("unknown", np.nan)
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

print("Тип Salary:", df["Salary"].dtype)
missing = pd.DataFrame({
    "пропусков": df.isna().sum(),
    "процент": (df.isna().mean() * 100).round(2),
})
missing

Тип Salary: float64

                  пропусков  процент
EmployeeID                0      0.0
FirstName                 0      0.0
LastName                  0      0.0
Department                0      0.0
Gender                    0      0.0
Age                       0      0.0
Salary                    3     20.0
HireDate                  0      0.0
PerformanceScore          0      0.0

In [17]:
# Эксперименты с dropna() — результат НЕ сохраняется в df
print("Исходный размер:                          ", df.shape)
print("dropna()  (axis=0, how='any')             ", df.dropna().shape)
print("dropna(axis=1)                            ", df.dropna(axis=1).shape)
print("dropna(how='all')                         ", df.dropna(how="all").shape)
print("dropna(axis=1, how='all')                 ", df.dropna(axis=1, how="all").shape)
print("dropna(subset=['Salary'])                 ", df.dropna(subset=["Salary"]).shape)
print("dropna(subset=['Age'])                    ", df.dropna(subset=["Age"]).shape)
print("dropna(thresh=9)  (нужны все 9 значений)  ", df.dropna(thresh=9).shape)
print("dropna(thresh=8)  (минимум 8 значений)    ", df.dropna(thresh=8).shape)

Исходный размер:                           (15, 9)
dropna()  (axis=0, how='any')              (12, 9)
dropna(axis=1)                             (15, 8)
dropna(how='all')                          (15, 9)

dropna(axis=1, how='all')                  (15, 9)
dropna(subset=['Salary'])                  (12, 9)
dropna(subset=['Age'])                     (15, 9)
dropna(thresh=9)  (нужны все 9 значений)   (12, 9)
dropna(thresh=8)  (минимум 8 значений)     (15, 9)

In [18]:
# Какие столбцы удаляет axis=1?
print("Столбцы, удалённые dropna(axis=1):", set(df.columns) - set(df.dropna(axis=1).columns))

Столбцы, удалённые dropna(axis=1): {'Salary'}

In [19]:
# Заполняем пустые значения Salary медианной зарплатой
median_salary = df["Salary"].median()
print("Медианная зарплата:", median_salary)

df["Salary"] = df["Salary"].fillna(median_salary)
print("Пропусков в Salary после заполнения:", df["Salary"].isna().sum())
df[["EmployeeID", "FirstName", "Salary"]]

Медианная зарплата: 71000.0
Пропусков в Salary после заполнения: 0

    EmployeeID  FirstName   Salary
0          101     Ainura  80000.0
1          102      Bakyt  65000.0
2          103    Gulnara  71000.0
3          103    Gulnara  71000.0
4          105     Nurlan  90000.0
5          106      Aigul  70000.0
6          107  Beksultan  71000.0
7          108    Aisuluu  62000.0
8          109      Ermek  85000.0
9          110     Nurgul  58000.0
10         111    Daniyar  72000.0
11         112     Aizhan  66000.0
12         113      Kubat  78000.0
13         114    Perizat  88000.0
14         115     Adilet  61000.0

### Задание 2 — Пояснение

- До очистки `isna()` нашёл только **2 пропущенные зарплаты (13,33%)**. После замены `"unknown"` на `NaN`
  пропусков стало **3 (20%)**. `pd.to_numeric(..., errors="coerce")` перевёл столбец в `float64`; любой другой
  неверный текст тоже стал бы `NaN`, а не вызвал ошибку.

**Что меняет каждый параметр `dropna()`:**

| Вызов | Результат | Смысл |
|---|---|---|
| `dropna()` | 12 строк | по умолчанию `axis=0, how="any"`: удаляется каждая **строка**, где есть хотя бы один NaN |
| `dropna(axis=1)` | 8 столбцов | удаляется каждый **столбец** с NaN — теряется весь столбец `Salary` |
| `dropna(how="all")` | 15 строк | строка удаляется, только если в ней **все** значения NaN — таких строк нет |
| `dropna(axis=1, how="all")` | 9 столбцов | столбец удаляется, только если он полностью пустой |
| `dropna(subset=["Salary"])` | 12 строк | NaN ищется **только в указанных столбцах** |
| `dropna(subset=["Age"])` | 15 строк | в Age нет NaN, поэтому ничего не удаляется |
| `dropna(thresh=9)` | 12 строк | остаются строки, где **не меньше 9 заполненных** значений (здесь = полные строки) |
| `dropna(thresh=8)` | 15 строк | остаются строки, где не меньше 8 значений — один NaN допускается |

Удаление убрало бы 20% сотрудников (или целый столбец), поэтому для такого маленького датасета оно не подходит.
Вместо этого пропущенные зарплаты **заполнены медианой (71 000)**. Медиана лучше среднего, потому что на неё
не влияют очень высокие или очень низкие зарплаты.

## Задание 3 — Стандартизация названий отделов

In [20]:
print("До:", df["Department"].unique())
print(df["Department"].value_counts())

До: <StringArray>
['IT', 'HR', 'it', 'Finance', 'Financing', 'Information Tecnology', 'finance']
Length: 7, dtype: str
Department
IT                       4
HR                       4
it                       2
Finance                  2
Financing                1
Information Tecnology    1
finance                  1
Name: count, dtype: int64

In [21]:
df["Department"] = (
    df["Department"]
    .str.strip()                                                       # убираем лишние пробелы
    .str.lower()                                                       # один регистр: "IT" / "it" -> "it"
    .str.replace("information tecnology", "it", regex=False)           # опечатка + полное название -> "it"
    .str.replace("financing", "finance", regex=False)                  # неверное слово -> "finance"
    .map({"it": "IT", "hr": "HR", "finance": "Finance"})               # официальные названия из `departments`
)

print("После:", df["Department"].unique())
print(df["Department"].value_counts())
print("Нераспознанных (NaN) отделов:", df["Department"].isna().sum())

После:

 <StringArray>
['IT', 'HR', 'Finance']
Length: 3, dtype: str
Department
IT         7
HR         4
Finance    4
Name: count, dtype: int64
Нераспознанных (NaN) отделов: 0

In [22]:
# Находим сотрудника с неверным возрастом
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
invalid_age = ~df["Age"].between(18, 70)          # реалистичный рабочий возраст
df[invalid_age]

,EmployeeID,FirstName,LastName,Department,Gender,Age,Salary,HireDate,PerformanceScore
4,105,Nurlan,Abdyldaev,Finance,M,150,90000.0,2021-11-20,4.0

In [23]:
# Решение: 150 лет невозможно, а настоящий возраст угадать нельзя (15? 50?),
# поэтому значение заменяется на пропуск, а не на придуманное число.
df.loc[invalid_age, "Age"] = np.nan
df.loc[df["EmployeeID"] == 105, ["EmployeeID", "FirstName", "LastName", "Age"]]

   EmployeeID FirstName   LastName  Age
4         105    Nurlan  Abdyldaev  NaN

### Задание 3 — Пояснение

- В столбце `Department` было **7 разных написаний** для 3 реальных отделов. Цепочка очистки:
  `str.strip()` убирает пробелы → `str.lower()` приводит к одному регистру → `str.replace()` исправляет опечатку
  `"information tecnology"` и неверное слово `"financing"` → `map()` превращает значения в официальные названия
  из таблицы `departments` (`IT`, `HR`, `Finance`).
- После очистки осталось **только 3 уникальных значения**: IT (7), HR (4), Finance (4), нераспознанных нет.
- **Неверный возраст:** у Nurlan Abdyldaev (ID 105) `Age = 150`, что невозможно. Допустимый диапазон — 18–70 лет.
  Я **не стала** заменять его медианой, потому что это было бы придуманное значение для реального человека; возраст
  заменён на пропуск (`NaN`), чтобы HR мог уточнить его у сотрудника. Остальные данные этого сотрудника верные,
  поэтому строка сохранена. Теперь Age — число (`float64` из-за NaN); в задании 5 он станет nullable integer.

## Задание 4 — Удаление дубликатов

In [24]:
# Для сравнения: в исходных данных НЕТ полных дубликатов, потому что "it"/"IT" и "F"/"f" различаются
print("Полных дубликатов в исходных данных:", employees.duplicated().sum())
print("Полных дубликатов после очистки:    ", df.duplicated().sum())
print("Повторяющихся EmployeeID:           ", df.duplicated(subset="EmployeeID").sum())
df[df.duplicated(keep=False)]

Полных дубликатов в исходных данных: 0
Полных дубликатов после очистки:     1
Повторяющихся EmployeeID:            1

,EmployeeID,FirstName,LastName,Department,Gender,Age,Salary,HireDate,PerformanceScore
2,103,Gulnara,Mamatova,IT,F,29.0,71000.0,2024-03-01,4.5
3,103,Gulnara,Mamatova,IT,F,29.0,71000.0,2024-03-01,4.5

In [25]:
# Эксперименты с drop_duplicates() — результат не сохраняется
print("Исходный размер:                         ", df.shape)
print("drop_duplicates()                        ", df.drop_duplicates().shape)
print("subset='EmployeeID', keep='first'        ", df.drop_duplicates(subset="EmployeeID", keep="first").shape)
print("subset='EmployeeID', keep='last'         ", df.drop_duplicates(subset="EmployeeID", keep="last").shape)
print("subset='EmployeeID', keep=False          ", df.drop_duplicates(subset="EmployeeID", keep=False).shape)

Исходный размер:                          (15, 9)
drop_duplicates()                         (14, 9)
subset='EmployeeID', keep='first'         (14, 9)
subset='EmployeeID', keep='last'          (14, 9)
subset='EmployeeID', keep=False           (13, 9)

In [26]:
# Какие индексы ID 103 остаются при каждом варианте keep?
for keep in ["first", "last", False]:
    kept = df.drop_duplicates(subset="EmployeeID", keep=keep)
    print(f"keep={keep!r:8} -> оставлены строки ID 103: {kept.index[kept['EmployeeID'] == 103].tolist()}")

keep='first'  -> оставлены строки ID 103: [2]
keep='last'   -> оставлены строки ID 103: [3]
keep=False    -> оставлены строки ID 103: []

In [27]:
# Шаг 1: удаляем полные дубликаты
df = df.drop_duplicates()
print("После удаления полных дубликатов:", df.shape)

# Шаг 2: удаляем дубликаты по EmployeeID (оставляем первую запись)
df = df.drop_duplicates(subset="EmployeeID", keep="first").reset_index(drop=True)
print("После удаления дубликатов по EmployeeID:", df.shape)
print("EmployeeID уникален:", df["EmployeeID"].is_unique)

После удаления полных дубликатов: (14, 9)
После удаления дубликатов по EmployeeID: (14, 9)
EmployeeID уникален: True

### Задание 4 — Пояснение

- В **исходных** данных `duplicated()` находит **0** полных дубликатов, потому что две записи ID 103 написаны
  по-разному (`"it"` и `"IT"`, `"F"` и `"f"`). После очистки в заданиях 1–3 они стали одинаковыми, и `duplicated()`
  находит **1** полный дубликат. Это показывает, что очистку нужно делать до удаления дубликатов.
- `drop_duplicates()` без параметров сравнивает **все столбцы**; `subset="EmployeeID"` сравнивает только ID и
  находит записи одного сотрудника, даже если они отличаются в других столбцах.
- `keep="first"` оставляет первое вхождение (индекс 2), `keep="last"` — последнее (индекс 3),
  а `keep=False` удаляет **все** копии — сотрудник 103 исчез бы полностью (13 строк), что неверно для подсчёта
  сотрудников.
- Итог: удалены полные дубликаты (15 → 14 строк), затем дубликаты по `EmployeeID` с `keep="first"` (больше не
  осталось, 14 строк). Теперь каждый `EmployeeID` уникален, и количество сотрудников верное: **14 человек**.

## Задание 5 — Преобразование типов данных

In [28]:
print("До:\n", df.dtypes, sep="")

До:
EmployeeID            int64
FirstName               str
LastName                str
Department              str
Gender                  str
Age                 float64
Salary              float64
HireDate                str
PerformanceScore     object
dtype: object

In [29]:
# Age -> nullable integer (Int64 умеет хранить <NA>, обычный int64 — нет)
df["Age"] = df["Age"].astype("Int64")
print("Тип Age:", df["Age"].dtype)
df["Age"].tolist()

Тип Age: Int64

[28, 35, 29, <NA>, 31, 33, 27, 30, 38, 26, 34, 29, 32, 31]

In [30]:
# Память до перевода в category
memory_before = df[["Department", "Gender"]].memory_usage(deep=True)

# Department и Gender -> category
df["Department"] = df["Department"].astype("category")
print("Тип Department:", df["Department"].dtype, "| категории:", list(df["Department"].cat.categories))

df["Gender"] = df["Gender"].astype("category")
print("Тип Gender:    ", df["Gender"].dtype, "| категории:", list(df["Gender"].cat.categories))

memory_after = df[["Department", "Gender"]].memory_usage(deep=True)
pd.DataFrame({"байт_как_текст": memory_before, "байт_как_category": memory_after})

Тип Department: category | категории: ['Finance', 'HR', 'IT']
Тип Gender:     category | категории: ['F', 'M']

            байт_как_текст  байт_как_category
Index                  132                132
Department             734                172
Gender                 700                114

In [31]:
# PerformanceScore -> число (текст "4.0" становится 4.0)
df["PerformanceScore"] = pd.to_numeric(df["PerformanceScore"], errors="coerce")
print("Тип PerformanceScore:", df["PerformanceScore"].dtype)
print("Пропусков после преобразования:", df["PerformanceScore"].isna().sum())

Тип PerformanceScore: float64
Пропусков после преобразования: 0

In [32]:
print("После:\n", df.dtypes, sep="")

После:
EmployeeID             int64
FirstName                str
LastName                 str
Department          category
Gender              category
Age                    Int64
Salary               float64
HireDate                 str
PerformanceScore     float64
dtype: object

### Задание 5 — Пояснение

- **`Age` → `Int64`** (nullable integer, с заглавной *I*). Обычный `int64` не может хранить пропуски, поэтому столбец
  с одним NaN остался бы `float64` (29.0, 150.0…). `Int64` хранит целые числа и показывает пропущенный возраст
  ID 105 как `<NA>`.
- **`Department`, `Gender` → `category`**, **`PerformanceScore` → `float64`** (текст `"4.0"` стал числом 4.0,
  новых пропусков не появилось).

**`object` и `category` — в чём разница:**

| `object` (текст) | `category` |
|---|---|
| каждая ячейка хранит свою полную строку Python | уникальные значения хранятся один раз (`categories`), а в ячейке — только маленький целочисленный код |
| можно записать любое значение, в том числе с опечаткой | допускаются только заданные категории |
| больше памяти, медленнее `groupby` / `value_counts` | меньше памяти и быстрее группировка — лучше всего для столбцов с **небольшим числом повторяющихся значений**, как Department или Gender |
| подходит для уникального текста (имена) | бесполезен для уникальных значений, например `FirstName` |

(В pandas 3 текстовые столбцы показываются как `str` вместо `object`, но разница с `category` та же.)
Таблица памяти выше показывает, что столбцы-категории занимают меньше памяти; на большом HR-датасете с тысячами
сотрудников экономия будет намного больше.

## Задание 6 — Разбор дат найма

In [33]:
print("До:   ", df["HireDate"].dtype)
df["HireDate"] = pd.to_datetime(df["HireDate"], format="%Y-%m-%d", errors="coerce")
print("После:", df["HireDate"].dtype)
print("Нераспознанных дат:", df["HireDate"].isna().sum())

До:    str
После: datetime64[us]
Нераспознанных дат: 0

In [34]:
# Извлекаем компоненты даты
weekdays_ru = {
    "Monday": "понедельник", "Tuesday": "вторник", "Wednesday": "среда", "Thursday": "четверг",
    "Friday": "пятница", "Saturday": "суббота", "Sunday": "воскресенье",
}
df["HireYear"] = df["HireDate"].dt.year
df["HireMonth"] = df["HireDate"].dt.month
df["HireWeekday"] = df["HireDate"].dt.day_name().map(weekdays_ru)

# Стаж в компании (в годах) на сегодняшнюю дату
today = pd.Timestamp.today().normalize()
df["YearsWorked"] = ((today - df["HireDate"]).dt.days / 365.25).round(1)

print("Дата расчёта:", today.date())
df[["EmployeeID", "FirstName", "HireDate", "HireYear", "HireMonth", "HireWeekday", "YearsWorked"]]

Дата расчёта:

 2026-10-22

,EmployeeID,FirstName,HireDate,HireYear,HireMonth,HireWeekday,YearsWorked
0,101,Ainura,2023-01-15,2023,1,воскресенье,3.8
1,102,Bakyt,2022-06-10,2022,6,пятница,4.4
2,103,Gulnara,2024-03-01,2024,3,пятница,2.6
3,105,Nurlan,2021-11-20,2021,11,суббота,4.9
4,106,Aigul,2023-08-05,2023,8,суббота,3.2
5,107,Beksultan,2020-05-12,2020,5,вторник,6.4
6,108,Aisuluu,2022-09-18,2022,9,воскресенье,4.1
7,109,Ermek,2021-03-25,2021,3,четверг,5.6
8,110,Nurgul,2019-07-14,2019,7,воскресенье,7.3
9,111,Daniyar,2023-04-18,2023,4,вторник,3.5
10,112,Aizhan,2020-10-02,2020,10,пятница,6.1
11,113,Kubat,2022-12-11,2022,12,воскресенье,3.9
12,114,Perizat,2021-08-30,2021,8,понедельник,5.1
13,115,Adilet,2023-06-22,2023,6,четверг,3.3

In [35]:
# Пример анализа по времени, который возможен только с datetime: число нанятых по годам
df["HireYear"].value_counts().sort_index()

HireYear
2019    1
2020    2
2021    3
2022    3
2023    4
2024    1
Name: count, dtype: int64

### Задание 6 — Пояснение

- `pd.to_datetime()` с `format="%Y-%m-%d"` перевёл `HireDate` из текста в **`datetime64`**. Точный формат ускоряет
  разбор и гарантирует, что день и месяц не перепутаются; `errors="coerce"` превратил бы неверную дату в `NaT`
  (все 14 дат оказались корректными).
- С помощью `.dt` извлечены **`HireYear`** (год), **`HireMonth`** (месяц) и **`HireWeekday`** (день недели,
  `dt.day_name()`, переведён на русский).
- **`YearsWorked`** (стаж) = (сегодня − HireDate) в днях ÷ 365,25 (средняя длина года с учётом високосных),
  округлено до одного знака. Так как расчёт идёт от сегодняшней даты, при повторном запуске значения немного растут.
- Теперь можно отвечать на вопросы по времени: например, сколько людей наняли в каждом году (таблица выше) или кто
  работает дольше всех (Nurgul Jumabaeva, нанята в 2019 году).

## Задание 7 — Переименование столбцов и объединение датасетов

In [36]:
df = df.rename(columns={"Salary": "MonthlySalary", "HireDate": "EmploymentStartDate"})
df.columns.tolist()

['EmployeeID',
 'FirstName',
 'LastName',
 'Department',
 'Gender',
 'Age',
 'MonthlySalary',
 'EmploymentStartDate',
 'PerformanceScore',
 'HireYear',
 'HireMonth',
 'HireWeekday',
 'YearsWorked']

In [37]:
# Left merge: сохраняем ВСЕХ сотрудников и добавляем информацию об отделе
hr = pd.merge(
    df,
    departments,
    left_on="Department",          # ключ в таблице сотрудников
    right_on="DepartmentName",     # ключ в таблице отделов (другое название)
    how="left",
    validate="many_to_one",        # много сотрудников -> один отдел
    indicator=True,                # показывает, нашлось ли совпадение для строки
)

print("Строк до объединения:", len(df), "| строк после:", len(hr))
print(hr["_merge"].value_counts())
print("\nПропуски, появившиеся после объединения:\n", hr[["DepartmentID", "DepartmentName", "Location"]].isna().sum(), sep="")

Строк до объединения:

 14 | строк после: 14
_merge
both          14
left_only      0
right_only     0
Name: count, dtype: int64

Пропуски, появившиеся после объединения:
DepartmentID      0
DepartmentName    0
Location          0
dtype: int64

In [38]:
# Почему очистка была важна: то же объединение на ИСХОДНЫХ названиях отделов
raw_merge = employees.merge(departments, left_on="Department", right_on="DepartmentName", how="left")
print("Строк без совпадения при исходных названиях:", raw_merge["DepartmentID"].isna().sum())
raw_merge.loc[raw_merge["DepartmentID"].isna(), ["EmployeeID", "Department", "DepartmentID", "Location"]]

Строк без совпадения при исходных названиях: 6

    EmployeeID             Department  DepartmentID Location
2          103                     it           NaN      NaN
6          107                    IT            NaN      NaN
10         111                     it           NaN      NaN
11         112              Financing           NaN      NaN
12         113  Information Tecnology           NaN      NaN
14         115                finance           NaN      NaN

In [39]:
# Наводим порядок: убираем вспомогательные/повторяющиеся столбцы и группируем связанные
hr = hr.drop(columns=["_merge", "DepartmentName"])
hr["DepartmentID"] = hr["DepartmentID"].astype("Int64")
hr["Department"] = hr["Department"].astype("category")   # merge возвращает ключ как текст, восстанавливаем category

hr = hr[[
    "EmployeeID", "FirstName", "LastName", "Gender", "Age",
    "DepartmentID", "Department", "Location",
    "MonthlySalary", "PerformanceScore",
    "EmploymentStartDate", "HireYear", "HireMonth", "HireWeekday", "YearsWorked",
]]
hr

,EmployeeID,FirstName,LastName,Gender,Age,DepartmentID,Department,Location,MonthlySalary,PerformanceScore,EmploymentStartDate,HireYear,HireMonth,HireWeekday,YearsWorked
0,101,Ainura,Asanova,F,28,1,IT,Bishkek,80000.0,4.2,2023-01-15,2023,1,воскресенье,3.8
1,102,Bakyt,Kyzylov,M,35,2,HR,Osh,65000.0,3.8,2022-06-10,2022,6,пятница,4.4
2,103,Gulnara,Mamatova,F,29,1,IT,Bishkek,71000.0,4.5,2024-03-01,2024,3,пятница,2.6
3,105,Nurlan,Abdyldaev,M,<NA>,3,Finance,Bishkek,90000.0,4.0,2021-11-20,2021,11,суббота,4.9
4,106,Aigul,Sultanova,F,31,2,HR,Osh,70000.0,3.9,2023-08-05,2023,8,суббота,3.2
5,107,Beksultan,Toktogulov,M,33,1,IT,Bishkek,71000.0,4.1,2020-05-12,2020,5,вторник,6.4
6,108,Aisuluu,Baisalova,F,27,3,Finance,Bishkek,62000.0,3.7,2022-09-18,2022,9,воскресенье,4.1
7,109,Ermek,Kadyrov,M,30,1,IT,Bishkek,85000.0,4.3,2021-03-25,2021,3,четверг,5.6
8,110,Nurgul,Jumabaeva,F,38,2,HR,Osh,58000.0,3.6,2019-07-14,2019,7,воскресенье,7.3
9,111,Daniyar,Turgunov,M,26,1,IT,Bishkek,72000.0,4.4,2023-04-18,2023,4,вторник,3.5
10,112,Aizhan,Ryskulova,F,34,3,Finance,Bishkek,66000.0,3.8,2020-10-02,2020,10,пятница,6.1
11,113,Kubat,Kadyraliev,M,29,1,IT,Bishkek,78000.0,4.2,2022-12-11,2022,12,воскресенье,3.9
12,114,Perizat,Baktybekova,F,32,2,HR,Osh,88000.0,4.0,2021-08-30,2021,8,понедельник,5.1
13,115,Adilet,Moldokulov,M,31,3,Finance,Bishkek,61000.0,3.9,2023-06-22,2023,6,четверг,3.3

### Задание 7 — Пояснение

- `rename(columns={...})` переименовал `Salary` → **`MonthlySalary`** и `HireDate` → **`EmploymentStartDate`**, чтобы
  смысл столбцов был понятен.
- Таблицы объединены через `pd.merge(..., left_on="Department", right_on="DepartmentName", how="left")`.
  `left_on`/`right_on` нужны, потому что ключевой столбец в таблицах называется по-разному.
  `how="left"` сохраняет **всех 14 сотрудников**, даже если отдел не найден.
  `validate="many_to_one"` проверяет, что каждый отдел встречается в `departments` только один раз, поэтому
  объединение не может задвоить сотрудников; `indicator=True` показал, что все строки — `both` (совпали).
- **Объединение не создало пропусков** — у каждого сотрудника есть `DepartmentID` и `Location`.
  Для сравнения: при объединении **исходных** данных **6 сотрудников остаются без отдела** (`"it"`, `" IT "`,
  `"Financing"`, `"Information Tecnology"`, `"finance"`) — это доказывает, зачем было нужно задание 3.
- Повторяющийся ключ `DepartmentName` и вспомогательный столбец `_merge` удалены, `Department` снова переведён в
  `category` (merge возвращает ключевой столбец как текст), а столбцы переставлены: сначала идентификаторы,
  связанные столбцы — рядом.

## Задание 8 — Финальная проверка и выводы

In [40]:
print("Строк и столбцов:", hr.shape)
print("\nТипы данных:\n", hr.dtypes, sep="")

Строк и столбцов: (14, 15)

Типы данных:
EmployeeID                      int64
FirstName                         str
LastName                          str
Gender                       category
Age                             Int64
DepartmentID                    Int64
Department                   category
Location                          str
MonthlySalary                 float64
PerformanceScore              float64
EmploymentStartDate    datetime64[us]
HireYear                        int32
HireMonth                       int32
HireWeekday                       str
YearsWorked                   float64
dtype: object

In [41]:
print("Пропуски:\n", hr.isna().sum(), sep="")

Пропуски:
EmployeeID             0
FirstName              0
LastName               0
Gender                 0
Age                    1
DepartmentID           0
Department             0
Location               0
MonthlySalary          0
PerformanceScore       0
EmploymentStartDate    0
HireYear               0
HireMonth              0
HireWeekday            0
YearsWorked            0
dtype: int64

In [42]:
print("Полных дубликатов строк:  ", hr.duplicated().sum())
print("Повторяющихся EmployeeID: ", hr["EmployeeID"].duplicated().sum())
print("Отделы:                   ", hr["Department"].unique().tolist())
print("Пол:                      ", hr["Gender"].unique().tolist())
print("Тип EmploymentStartDate:  ", hr["EmploymentStartDate"].dtype)
print("Диапазон возраста:        ", hr["Age"].min(), "-", hr["Age"].max())

Полных дубликатов строк:   0
Повторяющихся EmployeeID:  0
Отделы:                    ['IT', 'HR', 'Finance']
Пол:                       ['F', 'M']
Тип EmploymentStartDate:   datetime64[us]
Диапазон возраста:         26 - 38

In [43]:
# Автоматические проверки — ячейка выдаст ошибку, если какое-то правило нарушено
assert hr.shape[0] == 14
assert hr["EmployeeID"].is_unique
assert hr.duplicated().sum() == 0
assert set(hr["Department"]) == set(departments["DepartmentName"])
assert pd.api.types.is_datetime64_any_dtype(hr["EmploymentStartDate"])
assert pd.api.types.is_numeric_dtype(hr["MonthlySalary"]) and hr["MonthlySalary"].notna().all()
assert pd.api.types.is_numeric_dtype(hr["PerformanceScore"])
assert hr["Age"].dropna().between(18, 70).all()
assert hr[["DepartmentID", "Location"]].notna().all().all()
print("Все проверки пройдены. Исходный датасет не изменён:", employees.shape)

Все проверки пройдены. Исходный датасет не изменён: (15, 9)

In [44]:
# Первый взгляд на чистые данные: средняя зарплата и оценка по отделам
hr.groupby("Department", observed=True).agg(
    сотрудников=("EmployeeID", "count"),
    средняя_зарплата=("MonthlySalary", "mean"),
    средняя_оценка=("PerformanceScore", "mean"),
    локация=("Location", "first"),
).round(2)

            сотрудников  средняя_зарплата  средняя_оценка  локация
Department
Finance               4          69750.00            3.85  Bishkek
HR                    4          70250.00            3.82      Osh
IT                    6          76166.67            4.28  Bishkek

### Задание 8 — Выводы

**Итоговый результат:** чистая таблица `hr` — **14 уникальных сотрудников и 15 столбцов**. Все названия отделов
согласованы (IT, HR, Finance) и сопоставлены с таблицей `departments`, `EmploymentStartDate` имеет тип `datetime64`,
`MonthlySalary` и `PerformanceScore` — числовые, `Department`/`Gender` — категории, дубликатов нет.
Единственный оставшийся пропуск — **возраст сотрудника 105**, он оставлен как `<NA>` намеренно, потому что
настоящее значение неизвестно. Исходные датасеты `employees` и `departments` не изменены.

**Найденные проблемы и способы их решения:**

| Проблема | Метод и параметры | Зачем |
|---|---|---|
| Лишние пробелы (`" IT "`, `"Jumabaeva "`) | `str.strip()` | из-за пробелов одинаковые значения выглядят разными |
| Разный регистр (`m`/`f`, `MOLDOKULOV`) | `str.upper()`, `str.title()` | одно написание для одного значения |
| `"unknown"` и NaN в Salary (20%) | `replace("unknown", np.nan)`, `pd.to_numeric(errors="coerce")`, `fillna(медиана)` | скрытые пропуски; медиана устойчива к выбросам и сохраняет все строки |
| Несогласованные отделы (7 написаний) | `str.lower()`, `str.replace()`, `map()` | нужно для правильной группировки и объединения |
| Невозможный возраст 150 | проверка диапазона `between(18, 70)` → `NaN` | придуманное число хуже, чем известный пропуск |
| Дубликат сотрудника 103 | `drop_duplicates()`, затем `subset="EmployeeID", keep="first"` | правильное количество сотрудников |
| Неверные типы | `astype("Int64")`, `astype("category")`, `pd.to_numeric()` | вычисления, экономия памяти, пропуски в целых числах |
| Даты в виде текста | `pd.to_datetime(format="%Y-%m-%d")`, `.dt.year/.month/.day_name()` | анализ по времени, расчёт стажа |
| Непонятные названия столбцов / отдельные таблицы | `rename(columns=...)`, `pd.merge(how="left", left_on, right_on)` | понятные названия, локация отдела для каждого сотрудника |

**Почему подготовка данных важна перед HR-анализом.** Без очистки анализ дал бы неверные ответы: сотрудник 103
был бы посчитан дважды, отдел IT распался бы на четыре разных отдела, средний возраст завысило бы значение 150,
зарплаты нельзя было бы усреднить, потому что они были текстом, а 6 сотрудников потеряли бы информацию об отделе
при объединении. Решения о зарплатах, найме и оценке работы хороши ровно настолько, насколько хороши данные,
на которых они основаны, — *garbage in, garbage out* («мусор на входе — мусор на выходе»).